# Generated by Django 5.2 on 2025-04-19 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('plate_number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.FloatField()),
                ('loan', models.FloatField(blank=True, null=True)),
                ('interest', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cars',
                'ordering': ['brand', '-model'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('cost', models.FloatField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
            options={
                'verbose_name_plural': 'Services',
                'ordering': ['car', '-date'],
            },
        ),
    ]
